### ISSUE TITLE
Tooltip is not working

### ISSUE THREAD

**Issue by mdsina** [plesk/plesk-ext-sdk#28]
```
<Tooltip title={<Translate content="DNSView.nameFieldTooltip"/>}>
    <span style={{borderBottom: '1px dashed #ccc'}}><Translate content="DNSView.nameField"/>:</span>
</Tooltip>
```
Plesk: 17.9.8
plesk-ext-sdk: 0.5.4

Started from that: https://plesk.github.io/ui-library/#!/Tooltip
If i remove `span` element i've got https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]= error

How to deal with it?

**Comment by Fleuv** [comment]
I've got the same error when using one of the components from `@plesk/ui-library` through the `@plesk/plesk-ext-sdk` library. Thus far I discovered that only the `Translate` component works for me, all other components result in:

> Invariant Violation: "Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

**Comment by ekaragodin** [comment]
Can not reproduce on plesk-ext-sdk v0.5.5 and Plesk v18.0.18.
Please reopen if the issue still actual.
