### ISSUE TITLE
TypeError: can't redefine non-configurable property "Link"

### ISSUE THREAD

**Issue by mdsina** [plesk/plesk-ext-sdk#29]
**plesk version**: 17.9.13

**plesk-ext-sdk version**: 0.5.4

**steps to reproduce**

1) upload extension from https://github.com/plesk/ext-example/tree/next
2) Go to Overview screen

**actual result:**
`TypeError: can't redefine non-configurable property "Link"` in console
Nothing working

**expected result:**
Example works.

**Additional info:**
Looks like this clashes with `Link` export of `react-router-dom` shipped with Plesk

**Comment by mdsina** [comment]
@sibprogrammer @ekaragodin Please, provide workaround or ETA for fix, this affects extension in production scenario

**Comment by ekaragodin** [comment]
Fixed in 0.5.5.
